#!/usr/bin/env ash

set -eu

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

dir_put=$1

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > "${payload}" <&0

webhook_url="$(jq -r '.source.url' < "${payload}")"
build_status=$(jq -r '(.params.status // null)' < $payload)
git_repo="$(jq -r '(.params.git_repo // null)' < "${payload}")"

case "$build_status" in
  success)
    message_color='00FF00'
    ;;
  failure)
    message_color='FF0000'
    ;;
  *)
    exit 1
    ;;
esac

if [[ "$git_repo" != 'null' ]]; then
  dir_git="$dir_put/$git_repo"

  git_commit=$(git -C $dir_git rev-parse HEAD | jq -R -s .)
  git_branch=$(git -C $dir_git log -1 --format="format:%D" | jq -R -s .)

  git_author=$(git -C $dir_git log -1 --format=format:%an | jq -R -s .)
  git_author_date=$(git -C $dir_git log -1 --format=format:%ai | jq -R -s .)

  git_committer=$(git -C $dir_git log -1 --format=format:%cn | jq -R -s .)
  git_committer_date=$(git -C $dir_git log -1 --format=format:%ci | jq -R -s .)

  git_message=$(git -C $dir_git log -1 --format=format:%B | jq -R -s .)

  git_gpg_status=$(git -C $dir_git log -1 --format="format:%G?" | jq -R -s .)
  git_gpg_signer=$(git -C $dir_git log -1 --format="format:%GS" | jq -R -s .)
  git_gpg_key=$(git -C $dir_git log -1 --format="format:%GK" | jq -R -s .)
fi

message_title_link='${ATC_EXTERNAL_URL}/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}'


body="$(cat <<EOF
{
	"@type": "MessageCard",
	"@context": "https://schema.org/extensions",
	"summary": "Issue 176715375",
	"themeColor": "0078D7",
	"title": "Issue opened: \"Push notifications not working\"",
	"sections": [
		{
			"activityTitle": "Miguel Garcie",
			"activitySubtitle": "9/13/2016, 11:46am",
			"activityImage": "https://connectorsdemo.azurewebsites.net/images/MSC12_Oscar_002.jpg",
			"facts": [
				{
					"name": "Repository:",
					"value": "mgarcia\\test"
				},
				{
					"name": "Issue #:",
					"value": "176715375"
				}
			],
			"text": "There is a problem with Push notifications, they don't seem to be picked up by the connector."
		}
	],
	"potentialAction": [
		{
			"@type": "OpenUri",
			"name": "View in GitHub",
			"targets": [
				{
					"os": "default",
					"uri": "http://google.de"
				}
			]
		}
	]
}
EOF
)"

compact_body="$(echo "${body}" | jq -c '.')"

curl -X POST \
  "${webhook_url}" \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d "${compact_body}"

#
# print the output
#
timestamp="$(jq -n "{version:{time:\"$(date --utc +%FT%T.%3NZ)\"}}")"
echo "$timestamp" | jq -s add >&3
